version: '3'
services:
  web:
    build: .
    command: bundle exec rackup -o "0.0.0.0" -p 9292 config.ru
    volumes:
      - .:/locaweb-tweets
    ports:
      - "9292:9292"
volumes:
  web-data:
    driver: local
